.TH man 1 "07 june 2020" "1.0" "tor-tunnel man page"
.SH NAME
tor-tunnel \- Tunnel whole traffic through Tor Network using IPTABLES 
.SH SYNOPSIS
tor-tunnel [start|stop|change|ip]
.SH DESCRIPTION
Tor-Tunnel redirect whole traffic through Tor Network using IPTABLES. It also tunnel DNS queries through Tor. 
.SH OPTIONS
.P 
start  \- Start Tor Network Tunnel\n
.P 
stop   \- Stop Tor Network Tunnel\n
.P 
change \- Change Tor Network Node\n
.P 
ip     \- Show current externel IP\n
.SH SEE ALSO
tor(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Nouman Mahmood (noumanmhd@outlook.com)

